filename = input("Filename:")
ID = input("ID:")
title = input("Title:")
Des = input("DES:")
inp = input("input:")
outp = input("output:")
si = input("SI:")
so = input("SO:")
with open(filename,"w") as html:
    html.write("<html>\n")
    html.write("<head>\n")
    html.write('<link rel="stylesheet" type="text/css" href="new_sheet.css" />\n')
    html.write('</head>\n')
    html.write('<body id="problem_body">\n')
    html.write('<div class="navigation">\n')
    html.write('<table>\n')
    html.write('<tr>\n')
    html.write('<td class="GLW">Good Learning Web</td>\n')
    html.write('<td align="center" class="menu">\n')
    html.write('<a href="index.html" class="no_underline">HOME</a>\n')
    html.write('</td>\n')
    html.write('<td align="center" class="menu">\n')
    html.write('<a href="problem1.html" class="no_underline">Problems</a>\n')
    html.write('</td>\n')
    html.write('<td align="center" class="menu">\n')
    html.write('<a href="learning.html" class="no_underline">Learning</a>\n')
    html.write('</td>\n')
    html.write('<td align="center" class="menu">\n')
    html.write('<a href="user.html" class="no_underline">User</a>\n')
    html.write('</td>\n')
    html.write('</tr>\n')
    html.write('</table>\n')
    html.write('</div>\n')
    html.write('<div>\n')
    html.write('<a name="top"></a>\n')
    html.write('</div>\n')
    html.write('<br/>\n')
    html.write('<br/>\n')
    html.write('<br/><br/><br/><br/><br/><br/>\n')
    html.write('<div class="fill_div"></div>\n')
    html.write('<div class="container">\n')
    html.write('<div class="problem_dis wrap">\n')
    html.write('<li class="A_font">     ')
    html.write(ID)
    html.write(title)
    html.write('</li>\n')
    html.write('<div>\n')
    html.write('<li class="A_font list_ok" id="word_color">Description</li>\n')
    html.write('<p class="E_font">')
    html.write(Des+'</p>\n')
    html.write('</div>\n')
    html.write('<div>\n')
    html.write('<li class="A_font list_ok" id="word_color">Input</li>\n')
    html.write('<p class="E_font">')
    html.write(inp+'</p>\n')
    html.write('</div>\n')
    html.write('<div>\n')
    html.write('</div>\n')
    html.write('<li class="A_font list_ok" id="word_color">Output</li>\n')
    html.write('<p class="E_font">\n')
    html.write(outp + '</p>')
    html.write('<div class="example">\n')
    html.write('<li class="E_font" id="example_color">Sample Input 1</li>\n')
    html.write('<div class="example_box">\n')
    html.write('<pre>\n'+si+'</pre>\n')
    html.write('</div>\n')
    html.write('</div>\n')
    html.write('<div class="example">\n')
    html.write('<li class="E_font" id="example_color">Sample Output 1</li>\n')
    html.write('<div class="example_box">\n')
    html.write('<pre>\n'+so+'</pre>\n')
    html.write('</div>\n')
    html.write('</div>\n')
    html.write('</div>\n')
    html.write('<br/><br/>\n')
    html.write('<div class="problem_dis">\n')
    html.write('<div class="language">\n')
    html.write('<p>Language:</p>\n')
    html.write('</div>\n')
    html.write('<div class="language">\n')
    html.write('<select name="language" class="selection">\n')
    html.write('<option value="C" selected>C</option>\n')
    html.write('<option value="C++">C++</option>\n')
    html.write('<option value="Python2">Python2</option>\n')
    html.write('<option value="Python3">Python3</option>\n')
    html.write('</select>\n')
    html.write('</div>\n')
    html.write('<div class="input_box">\n')
    html.write('<div id="text_size">\n')
    html.write('<textarea rows="22" cols="50" spellcheck="false" id="text_font"></textarea>\n')
    html.write('</div>\n')
    html.write('<div>\n')
    html.write('<a href="judge.html">\n')
    html.write('<input type="button" value="submit" id="sub">\n')
    html.write('</a>\n')
    html.write('</div>\n')
    html.write('</div>\n')
    html.write('</div>\n')
    html.write('</div>\n')
    html.write('<div class="fill_div up">\n')
    html.write('<div class="margin_r">\n')
    html.write('<a href="#top">\n')
    html.write('<img src="up.png" alt="go to top" align ="right" width="50" height="50" transition=" all 0.6s" >\n')
    html.write('</a>\n')
    html.write('</div>\n')
    html.write('</div>\n')
    html.write('<br/><br/> <br/><br/>\n')
    html.write('<div class="D_font" >\n')
    html.write('<p id="text_pos">\n')
    html.write('powered by Leyu ZHANG\n')
    html.write('</p>\n')
    html.write('</div>\n')
    html.write('</body>\n')
    html.write('</html>\n')